name: Update Sponsors Data

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  build:
    name: Commit if needed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get typescript-eslint Github app token
        id: get_token
        uses: machine-learning-apps/actions-app-token@2d92b2a2bb7030dca3dd14975ae44799debed2e8
        with:
          APP_PEM: ${{ secrets.GH_APP_PEM }}
          APP_ID: ${{ secrets.GH_APP_ID }}

      - uses: Codecademy/run-on-yarn@v1
        with:
          command: generate-sponsors
          node-version: 16

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ steps.get_token.outputs.app_token }}
          commit-message: "chore: update sponsors"
          title: "chore: update sponsors"
          body: "💸"
          branch: auto-update-sponsors
